{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-zook.serviceAccountName" . }}
  labels:
{{ include "kafka-zook.labels" . | nindent 4 }}
{{- end -}}
